// AUTO-GENERATED by scripts/emit-csp-hash.ts — do not edit
export const FOUC_SCRIPT = "(function(){try{var s=JSON.parse(localStorage.getItem('evandro.state.v1')||'{}');if(s.theme)document.documentElement.dataset.theme=s.theme;}catch(e){}})();";
