import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

// BYTE-STABLE — do NOT reformat or modify this string without re-running this script
const FOUC_SCRIPT =
  `(function(){try{var s=JSON.parse(localStorage.getItem('evandro.state.v1')||'{}');` +
  `if(s.theme)document.documentElement.dataset.theme=s.theme;}catch(e){}})();`;

const hash   = createHash('sha256').update(FOUC_SCRIPT).digest('base64');
const sha256 = `'sha256-${hash}'`;

const headersPath = join(ROOT, 'public/_headers');
const current     = readFileSync(headersPath, 'utf-8');

// Replace the script-src directive
const updated = current.replace(
  /script-src [^;]+;/,
  `script-src 'self' ${sha256};`,
);

writeFileSync(headersPath, updated);
console.log(`[csp] script-src hash → ${sha256}`);

// Emit the script constant so index.astro can inline it
const scriptPath = join(ROOT, 'src/terminal/_fouc.ts');
writeFileSync(
  scriptPath,
  `// AUTO-GENERATED by scripts/emit-csp-hash.ts — do not edit\n` +
  `export const FOUC_SCRIPT = ${JSON.stringify(FOUC_SCRIPT)};\n`,
);
console.log('[csp] wrote src/terminal/_fouc.ts');
